###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cashbox-api-mailhog
    ports:
      - "8081:8025"

  mysql:
    image: mysql:5.7
    container_name: cashbox-api-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=cashbox
      - MYSQL_USER=cashbox
      - MYSQL_PASSWORD=cashbox
    ports:
      - "8082:3306"

  webserver:
    image: nginx:alpine
    container_name: cashbox-api-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: cashbox-api-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cashbox-api-phpmyadmin
    ports:
      - 8083:80
    volumes:
      - /sessions
    external_links:
      - cashbox-api-mysql:db